# Generated by Django 4.1 on 2022-08-29 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='subtask',
            new_name='task_asociated',
        ),
    ]
