# Generated by Django 4.1 on 2022-09-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_subtask_subtask_task_asociated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Task_despcription',
            new_name='Task_description',
        ),
    ]
